// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZDJTGNIo2uQ7NovFJsGAlqR52nUYNYKM',
    appId: '1:349551066945:web:0df351397c322a336cabc0',
    messagingSenderId: '349551066945',
    projectId: 'grocery-app-73f20',
    authDomain: 'grocery-app-73f20.firebaseapp.com',
    storageBucket: 'grocery-app-73f20.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoSt4bWw-WHXZ85MAFoOTx9S5dP1y5JFs',
    appId: '1:349551066945:android:4f94cc45094efe726cabc0',
    messagingSenderId: '349551066945',
    projectId: 'grocery-app-73f20',
    storageBucket: 'grocery-app-73f20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDipF7XQ1jegc5M0eWnE1hx6cAZFqhEEvA',
    appId: '1:349551066945:ios:9a68c279cbfd92846cabc0',
    messagingSenderId: '349551066945',
    projectId: 'grocery-app-73f20',
    storageBucket: 'grocery-app-73f20.firebasestorage.app',
    iosBundleId: 'com.example.groceryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDipF7XQ1jegc5M0eWnE1hx6cAZFqhEEvA',
    appId: '1:349551066945:ios:9a68c279cbfd92846cabc0',
    messagingSenderId: '349551066945',
    projectId: 'grocery-app-73f20',
    storageBucket: 'grocery-app-73f20.firebasestorage.app',
    iosBundleId: 'com.example.groceryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZDJTGNIo2uQ7NovFJsGAlqR52nUYNYKM',
    appId: '1:349551066945:web:3bd881baf90092d36cabc0',
    messagingSenderId: '349551066945',
    projectId: 'grocery-app-73f20',
    authDomain: 'grocery-app-73f20.firebaseapp.com',
    storageBucket: 'grocery-app-73f20.firebasestorage.app',
  );

}